
---
- name: Verificar si el servicio  está corriendo en Windows Server
  hosts: all
  gather_facts: no
  vars:
    servicio_win: Spooler

  tasks:
    - name: Obtener estado del servicio 
      win_shell: |
        $service = Get-Service -Name "{{ servicio_win }}"
        $service.Status
      register: service_status

    - name: Mostrar estado del servicio 
      debug:
        msg: "Estado actual de '{{ servicio_win }}': {{ service_status.stdout }}"


