---
- name: Desplegar sitio web "Hola Mundo" con IIS en puerto 8080
  hosts: all
  collections:
    - ansible.windows
  tasks:

    - name: Instalar IIS
      ansible.windows.win_feature:
        name: Web-Server
        state: present
        include_sub_features: true

    - name: Asegurar que IIS esté iniciado y habilitado
      ansible.windows.win_service:
        name: W3SVC
        state: started
        start_mode: auto

    - name: Reemplazar contenido de la página de inicio
      ansible.windows.win_copy:
        dest: 'C:\inetpub\wwwroot\index.html'
        content: |
          <html>
            <body>
              <h1>¡Hola mundo desde IIS!</h1>
            </body>
          </html>

    - name: Cambiar el puerto del sitio por defecto a 8080
      ansible.windows.win_shell: |
        Import-Module WebAdministration
        Set-ItemProperty "IIS:\Sites\Default Web Site" -Name bindings -Value @{protocol="http";bindingInformation="*:8080:"}

    - name: Abrir puerto 8080 en el firewall de Windows
      ansible.windows.win_firewall_rule:
        name: "Abrir puerto 8080 para IIS"
        localport: 8080
        protocol: tcp
        action: allow
        direction: in
        state: present
        enabled: yes
