---
- name: Crear script en Windows Server 2022
  hosts: all
  gather_facts: no
  tasks:
    - name: Asegurarse de que el directorio C:\Scripts exista
      win_file:
        path: C:\Scripts
        state: directory

    - name: Crear el archivo myscript.ps1 con contenido
      win_copy:
        dest: C:\Scripts\myscript.ps1
        content: |
          # Define the service name
          $serviceName = "servicedesk"

          # Get the status of the service
          $service = Get-Service -Name $serviceName

          # Check if the service is stopped
          if ($service.Status -eq 'Stopped') {
              # Define email parameters
              $EmailFrom = "isphelpdeskservice@claropr.com"
              $EmailTo = "noreply@claropr.com"
              $Subject = "Service Alert: $serviceName has stopped"
              $Body = "The service $serviceName has stopped on $(Get-Date)."

              # Send the email
              Send-MailMessage -From $EmailFrom -To $EmailTo -Subject $Subject -Body $Body -SmtpServer "IP Address"
          }